
name = makoa

export_threads = 2
pooling = 0

#import = tcp_client localhost:10000
#import = tcp_server 10000
#import = pipe /dev/shm/huobi_pp
import = mmap_cp /dev/shm/huobi_cp

#export = tcp_client localhost:10000
#export = tcp_server 10000
#export = ying
#export = ying RIH0 100
#export = ying SVH0 100
#export = ying btcusdt 100

#export = file csv rename_new logs/data.csv
#export = file bin rename_new logs/data.bin
#export = mysql rename_new 192.168.1.4 0 mgame mgame_user mgame_pass
export = stat bla1;ying btcusdt 100;stat bla2
#export = stat i;log_messages;stat o
#export = log_messages

